#ifndef PSA_VAN_PACKET_IDEN_H
#define PSA_VAN_PACKET_IDEN_H

// VAN IDENtifiers

enum psa_van_iden
{
    PSA_VAN_IDEN_VIN = 0xE24,
    PSA_VAN_IDEN_ENGINE = 0x8A4,
    PSA_VAN_IDEN_HEAD_UNIT_STALK = 0x9C4,
    PSA_VAN_IDEN_LIGHTS_STATUS = 0x4FC,
    PSA_VAN_IDEN_DEVICE_REPORT = 0x8C4,
    PSA_VAN_IDEN_CAR_STATUS1 = 0x564,
    PSA_VAN_IDEN_CAR_STATUS2 = 0x524,
    PSA_VAN_IDEN_RPM = 0x824,
    PSA_VAN_IDEN_DASHBOARD_BUTTONS = 0x664,
    PSA_VAN_IDEN_HEAD_UNIT = 0x554,
    PSA_VAN_IDEN_TIME = 0x984,
    PSA_VAN_IDEN_AUDIO_SETTINGS = 0x4D4,
    PSA_VAN_IDEN_MFD_STATUS = 0x5E4,
    PSA_VAN_IDEN_AIRCON1 = 0x464,
    PSA_VAN_IDEN_AIRCON2 = 0x4DC,
    PSA_VAN_IDEN_CDCHANGER = 0x4EC,
    PSA_VAN_IDEN_SATNAV_STATUS_1 = 0x54E,
    PSA_VAN_IDEN_SATNAV_STATUS_2 = 0x7CE,
    PSA_VAN_IDEN_SATNAV_STATUS_3 = 0x8CE,
    PSA_VAN_IDEN_SATNAV_GUIDANCE_DATA = 0x9CE,
    PSA_VAN_IDEN_SATNAV_GUIDANCE = 0x64E,
    PSA_VAN_IDEN_SATNAV_REPORT = 0x6CE,
    PSA_VAN_IDEN_MFD_TO_SATNAV = 0x94E,
    PSA_VAN_IDEN_SATNAV_TO_MFD = 0x74E,
    PSA_VAN_IDEN_SATNAV_DOWNLOADING = 0x6F4,
    PSA_VAN_IDEN_SATNAV_DOWNLOADED1 = 0xA44,
    PSA_VAN_IDEN_SATNAV_DOWNLOADED2 = 0xAC4,
    PSA_VAN_IDEN_WHEEL_SPEED = 0x744,
    PSA_VAN_IDEN_ODOMETER = 0x8FC,
    PSA_VAN_IDEN_COM2000 = 0x450,
    PSA_VAN_IDEN_CDCHANGER_COMMAND = 0x8EC,
    PSA_VAN_IDEN_MFD_TO_HEAD_UNIT = 0x8D4,
    PSA_VAN_IDEN_AIR_CONDITIONER_DIAG = 0xADC,
    PSA_VAN_IDEN_AIR_CONDITIONER_DIAG_COMMAND = 0xA5C,
    PSA_VAN_IDEN_ECU = 0xB0E,
};

#endif